#!/usr/bin/perl
# begin_generated_IBM_Teracloud_ApS_copyright_prolog               
#                                                                  
# This is an automatically generated copyright prolog.             
# After initializing,  DO NOT MODIFY OR MOVE                       
# **************************************************************** 
# THIS SAMPLE CODE IS PROVIDED ON AN "AS IS" BASIS.                
# TERACLOUD APS AND IBM MAKES NO REPRESENTATIONS OR WARRANTIES,    
# EXPRESS OR IMPLIED, CONCERNING  USE OF THE SAMPLE CODE, OR THE   
# COMPLETENESS OR ACCURACY OF THE SAMPLE CODE. TERACLOUD APS       
# AND IBM DOES NOT WARRANT UNINTERRUPTED OR ERROR-FREE OPERATION   
# OF THIS SAMPLE CODE. TERACLOUD APS AND IBM IS NOT RESPONSIBLE FOR THE 
# RESULTS OBTAINED FROM THE USE OF THE SAMPLE CODE OR ANY PORTION  
# OF THIS SAMPLE CODE.                                             
#                                                                  
# LIMITATION OF LIABILITY. IN NO EVENT WILL IBM BE LIABLE TO ANY   
# PARTY FOR ANY DIRECT, INDIRECT, SPECIAL OR OTHER CONSEQUENTIAL   
# DAMAGES FOR ANY USE OF THIS SAMPLE CODE, THE USE OF CODE FROM    
# THIS [ SAMPLE PACKAGE,] INCLUDING, WITHOUT LIMITATION, ANY LOST  
# PROFITS, BUSINESS INTERRUPTION, LOSS OF PROGRAMS OR OTHER DATA   
# ON YOUR INFORMATION HANDLING SYSTEM OR OTHERWISE.                
#                                                                  
# (C) Copyright Teracloud ApS 2024, 2025, IBM Corp. 2014, 2014     
# All Rights reserved.                                             
#                                                                  
# end_generated_IBM_Teracloud_ApS_copyright_prolog                 

use strict;
use warnings;

# Checks the correctness of the "data/multipleSources.dat" file generated by 
# sample::MultipleSources. Output tuples where the first attribute has a
# value of '0' should be strictly increasing and only have even numbers.
# Output tuples where the first attribute has a value of '1' should be
# strictly increasing and only have odd numbers.
my $filename = "data/multipleSources.dat";
open FILE, "<", $filename 
  or die "Cannot open application output file $filename: $!";

my %data = ();
$data{0} = 0; # First value expected for beatId = 0
$data{1} = 1; # First value expected for beatId = 1

while (my $line = <FILE>) {
  chomp($line);
  if ($line =~ m/#reset|#checkpoint|#retire|#drain/) {
    next;
  }
  my @fields = split(/,/, $line);
  my $size = @fields;
  if ($size != 2) {
    print "Skipping incomplete line: $line\n";
    next;
  }
  if ($data{$fields[0]} != $fields[1]) {
    print "Error: expected $data{$fields[0]} and got $fields[1]. Line: $line\n";
    exit(1);
  }
  $data{$fields[0]} = $fields[1] + 2;
}
print "SUCCESS\n";
